## Python_Advance_Assignment_22

<b>1. What are the benefits of the built-in array package, if any?</b><br>Answer:<br>
When dealing with a huge number of elements, arrays use less memory than lists and they offer faster execution than lists.<br> More efficient in performing the mathematical operations than the list.


<b>2. What are some of the array package's limitations?</b><br>Answer:<br>
- Contains elements of same data types
- Need to import the module explicitly to declare an array
- It is difficult to modify an array since addition, deletion and update operation is performed on a single element at a time
- To print or access array elements, we will require an explicit loop


<b>3. Describe the main differences between the array and numpy packages.</b><br>Answer:<br>

The major difference between the built-in array module and numpy array. A built-in __array__ is quite strict about the storage of objects in itself. It permits only that type of data to be stored in itself, which has been specified strictly by the typecode. We cannot store float value when typecode specifies that, int data has to be stored in the built-in array. However __numpy__ array is a bit tolerant or lenient in that matter, it will upcast or downcast and try to store the data at any cost. (Float was converted to int, even if that resulted in loss of data after decimal).

<b>4. Explain the distinctions between the empty, ones, and zeros functions.</b><br>Answer:<br>
__empty()__ , __zeros()__ and __ones()__ are the NumPy library functions to create two different arrays.<br> __zeros()__ function is used to create an array based on the particular shape and type. All array elements are initialized to 0, which is created by the zeros() function. 
<br>__ones()__ function works like the zeros() function. But the elements of the array created by the ones() function are initialized to  1.<br>
__empty()__ Returns a new array of given shape and type, with random values.
This function is used to create an array without initializing the entries of given shape and type. Just like numpy.zeros(), the numpy.empty() function doesn't set the array values to zero, and it is quite faster than the numpy.zeros().

<b>5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?</b><br>Answer:<br>
The _callable_ parameter is a function which is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis. For example, if shape were (2, 2), then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]]).

<b>6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?</b><br>Answer:<br>
The scalar _n_ is added to the each item of the array.

In [5]:
#Example
import numpy as np
A=np.array([[2,3,4,5],[2,3,1,2]])
A+3.4
A

array([[2, 3, 4, 5],
       [2, 3, 1, 2]])

<b>7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?</b><br>Answer:<br>
No, _array-to-scalar operations_ cannot use operation-assign operators. If used it will show error. 

In [6]:
#Example
import numpy as np
A=np.array([[2,3,4,5],[2,3,1,2]])
A+=3.2
A

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

<b>8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?</b><br>Answer:<br>
Yes, numpy array can have fixed-length strings. If we allocate a longer string it will loose information.

In [13]:
#Example
import numpy as np
A=np.array(["aaaaaaaa"],dtype='S5')
A

array([b'aaaaa'], dtype='|S5')

<b>9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?</b><br>Answer:<br>
When you combine two numpy arrays using an operation the result is an array containing the results of the operation. 

In [17]:
#Example
import numpy as np
A=np.array([[2,3,4], [5,3,6]])
B=np.array([[1,1,1], [1,1,1]])
A+B

array([[3, 4, 5],
       [6, 4, 7]])

<b>10. What is the best way to use a Boolean array to mask another array?</b><br>Answer:<br>
Best way to use a Boolean array to mask is to pass Boolean array inside [] operator for target array.

In [26]:
#Example

# importing NumPy
import numpy as np
# Creating a NumPy array
arr = np.arange(10)
# Printing our array to observe
print(arr)

#Boolean array
b_array=[True, False,False,True,True,False,True,True,True,True]
# Using boolean masking to filter elements
print(arr[b_array])

[0 1 2 3 4 5 6 7 8 9]
[0 3 4 6 7 8 9]


<b>11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.</b><br>Answer:<br>
Standard Deviation in Python can be found using:
1. statistics.stdev() function
2. numpy.std() function
3. Pandas Dataframe.std() module function

Execution time least to most is- 
- numpy.std() (least)
- statistics.stdev()
- Dataframe.std() (most)

<b>12. What is the dimensionality of a Boolean mask-generated array?</b><br>Answer:<br>
One-dimension

In [81]:
##Example

import numpy as np
# Creating a NumPy array
arr = np.array([[1,3,2],[4,3,6]])
# Printing our array to observe
print("arr:")
print(arr)

#Boolean array
b_array=np.array([[True, False,False],[True,True,False]])
# Using boolean masking to filter elements
print("masked arr=",arr[b_array])

arr:
[[1 3 2]
 [4 3 6]]
masked arr= [1 4 3]
